language: groovy
jdk:
- oraclejdk8
before_install:
- ./gradlew clean
after_success:
- ./gradlew cobertura
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: openshift
  user: fmillone
  password:
    secure: YrQgq2Uww2hyTF3zQVVLxgD5AYSeYz1tHD6G3riBD8Oymm61xqPJi2glAZmf1i0G/6sa11r/Fr5gv1zfPwae+a7GOXtuQtd7JNkibyTrVBf6JjXf8NXPMe0CMCyTw7mklw6lzK2lOHMHvqUlkJbSskG+JogqvcbjtPhvQtIGhuaj2ceb/cAU21vQOVwMoI3Dc7k/ZhbCsTVVlUP92F2fzn8QtwqTI8nMwgCuh66V6gGhMN6XOQCaX1c71RVbkpHEpUyoQr5yDmaoAlORNO5WnPtR2dOfTlB52/y1L6TJI31OxlTnvh7aISLyymNQ4jkDoKe3/ECe9tUaaGnB3X485BJ8AFBHoLKU20CdCpq83kaNxtMcPQLmh7xnhaYwtwaLR6Dsd/0uDIQQEujoRQKnoySoFqDWeiexIiZ7sOcsZMEG+1DPrR0JCUNY9ATwg8CbnbSKp7FPrGTkzFXO6CJtbEnAiSzKoJ9uJpQ5FvDp2rszh0SALr3XvMJckDYPjySlq8EBFf5ukzaMa5hCOwe/6/Wh76t0b9rrFMsVR7bRXhJGghCSmkAOP02g+oFieCDawq3Avo+HQUqW5rRoyPT3HDXmGtFdSKDNZ4oVoe6Z+2RxUDc7Qh7q9c31wosWa8vRGkV+AOfWljp8AvofITCtcJiU1jY9MZKmnjp75/NT3RM=
  app: awesomepp
  domain: fmillone
  on:
    repo: fmillone/my-awesome-planning-poker
